# Generated by Django 2.0.7 on 2020-10-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
